steps:
  # Step 1: 下載 GCS 檔案到本地建置目錄
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p AniwalkServer/wwwroot
        gsutil -m cp -r gs://aniwalk_wwwroot/* AniwalkServer/wwwroot/
        # 驗證在 Cloud Build log 看到實際下載了哪些檔案。
        ls -lR AniwalkServer/wwwroot

  # Step 2: 建置 Docker 映像檔
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aniwalk-server', '.']

images:
  - 'gcr.io/$PROJECT_ID/aniwalk-server'