// <auto-generated />
using System;
using AniwalkServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AniwalkServer.Data;

#nullable disable

namespace AniwalkServer.Migrations
{
    [DbContext(typeof(AniwalkDBContext))]
    [Migration("20250717040337_InitialLogin")]
    partial class InitialLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AniwalkServer.Models.Animes", b =>
                {
                    b.Property<string>("AnimeID")
                        .HasMaxLength(4)
                        .HasColumnType("char");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HeaderPhoto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AnimeID");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AniwalkServer.Models.Comments", b =>
                {
                    b.Property<string>("CommentID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("ParentCommentID")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("SN");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AniwalkServer.Models.Countries", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("char");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AniwalkServer.Models.Login", b =>
                {
                    b.Property<string>("Account")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Account");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.ToTable("Login");
                });

            modelBuilder.Entity("AniwalkServer.Models.MemberRoles", b =>
                {
                    b.Property<byte>("RoleID")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoleID");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(10)
                        .HasColumnType("char");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("RoleID")
                        .HasColumnType("tinyint");

                    b.HasKey("MemberID");

                    b.HasIndex("CountryCode");

                    b.HasIndex("RoleID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AniwalkServer.Models.Visits", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<string>("AnimeID")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MainText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("VisitedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SN");

                    b.HasIndex("AnimeID");

                    b.HasIndex("CountryCode");

                    b.HasIndex("MemberID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AniwalkServer.Models.VisitsPhotos", b =>
                {
                    b.Property<string>("PhotoID")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("PhotoID");

                    b.HasIndex("MemberID");

                    b.HasIndex("SN");

                    b.ToTable("VisitsPhotos");
                });

            modelBuilder.Entity("AniwalkServer.Models.VisitsTags", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SN");

                    b.ToTable("VisitsTags");
                });

            modelBuilder.Entity("VisitsVisitsTags", b =>
                {
                    b.Property<int>("VisitsSN")
                        .HasColumnType("int");

                    b.Property<int>("VisitsTagSN")
                        .HasColumnType("int");

                    b.HasKey("VisitsSN", "VisitsTagSN");

                    b.HasIndex("VisitsTagSN");

                    b.ToTable("VisitsVisitsTags");
                });

            modelBuilder.Entity("AniwalkServer.Models.Comments", b =>
                {
                    b.HasOne("AniwalkServer.Models.Members", "Member")
                        .WithMany("Comments")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Comments", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentID");

                    b.HasOne("AniwalkServer.Models.Visits", "Visit")
                        .WithMany()
                        .HasForeignKey("SN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("ParentComment");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("AniwalkServer.Models.Login", b =>
                {
                    b.HasOne("AniwalkServer.Models.Members", "Member")
                        .WithOne("Login")
                        .HasForeignKey("AniwalkServer.Models.Login", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.HasOne("AniwalkServer.Models.Countries", "Country")
                        .WithMany("Members")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.MemberRoles", "MemberRole")
                        .WithMany("Members")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MemberRole");
                });

            modelBuilder.Entity("AniwalkServer.Models.Visits", b =>
                {
                    b.HasOne("AniwalkServer.Models.Animes", "Anime")
                        .WithMany("Visits")
                        .HasForeignKey("AnimeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Countries", "Country")
                        .WithMany("Visits")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Members", "Member")
                        .WithMany("Visits")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Country");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AniwalkServer.Models.VisitsPhotos", b =>
                {
                    b.HasOne("AniwalkServer.Models.Members", "Member")
                        .WithMany("VisitsPhotos")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Visits", "Visit")
                        .WithMany("VisitsPhotos")
                        .HasForeignKey("SN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("VisitsVisitsTags", b =>
                {
                    b.HasOne("AniwalkServer.Models.Visits", null)
                        .WithMany()
                        .HasForeignKey("VisitsSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.VisitsTags", null)
                        .WithMany()
                        .HasForeignKey("VisitsTagSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniwalkServer.Models.Animes", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("AniwalkServer.Models.Comments", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("AniwalkServer.Models.Countries", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("AniwalkServer.Models.MemberRoles", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Login");

                    b.Navigation("Visits");

                    b.Navigation("VisitsPhotos");
                });

            modelBuilder.Entity("AniwalkServer.Models.Visits", b =>
                {
                    b.Navigation("VisitsPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
