// <auto-generated />
using System;
using AniwalkServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniwalkServer.Migrations
{
    [DbContext(typeof(AniwalkDBContext))]
    partial class AniwalkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimesCountries", b =>
                {
                    b.Property<string>("AnimesAnimeID")
                        .HasColumnType("char(4)");

                    b.Property<string>("CountriesCountryCode")
                        .HasColumnType("char(3)");

                    b.HasKey("AnimesAnimeID", "CountriesCountryCode");

                    b.HasIndex("CountriesCountryCode");

                    b.ToTable("AnimesCountries");
                });

            modelBuilder.Entity("AniwalkServer.Models.Animes", b =>
                {
                    b.Property<string>("AnimeID")
                        .HasMaxLength(4)
                        .HasColumnType("char");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HeaderPhoto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AnimeID");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AniwalkServer.Models.Countries", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("char");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(10)
                        .HasColumnType("char");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MemberID");

                    b.HasIndex("CountryCode");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AniwalkServer.Models.Visits", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<string>("AnimeID")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MainText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.HasKey("SN");

                    b.HasIndex("AnimeID");

                    b.HasIndex("CountryCode");

                    b.HasIndex("MemberID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("AnimesCountries", b =>
                {
                    b.HasOne("AniwalkServer.Models.Animes", null)
                        .WithMany()
                        .HasForeignKey("AnimesAnimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Countries", null)
                        .WithMany()
                        .HasForeignKey("CountriesCountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.HasOne("AniwalkServer.Models.Countries", "Country")
                        .WithMany("Members")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AniwalkServer.Models.Visits", b =>
                {
                    b.HasOne("AniwalkServer.Models.Animes", "Anime")
                        .WithMany("Visits")
                        .HasForeignKey("AnimeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Countries", "Country")
                        .WithMany("Visits")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AniwalkServer.Models.Members", "Member")
                        .WithMany("Visits")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Country");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AniwalkServer.Models.Animes", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("AniwalkServer.Models.Countries", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("AniwalkServer.Models.Members", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
